### ISSUE TITLE
Is this still a problem with Rails 5.2?

### ISSUE THREAD

**Issue by ghost** [mwpastore/rack-protection-maximum_cookie#1]
Is this still a problem with Rails 5.2?

**Comment by mwpastore** [comment]
Unfortunately, yes.

**Comment by ghost** [comment]
@mwpastore any news about to insert this in Rails 5.2?

**Comment by mwpastore** [comment]
I'm as ignorant about it now as I was when I first wrote the README. I'll try to make some time this weekend to figure it out. Thanks for your interest!
